name: filesaverz
description: A customable file saver and file picker package that makes it easy for user to browse folder and save file or pick files in android.
version: 3.2.1
homepage: https://inidia.app
repository: https://github.com/Nialixus/filesaverz
issue_tracker: https://github.com/Nialixus/filesaverz/issues
funding: 
  - https://ko-fi.com/nialixus
screenshots:
  - description: 'File Saver Z Logo'
    path: logo.png
topics:
  - utility
  - file
  - saver
  - picker
  - android

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: app.inidia.filesaver
        pluginClass: FilesaverPlugin
